const companies = [
  "10up",
  "23andme",
  "78 capital",
  "a cloud guru",
  "a10 networks",
  "abbvie",
  "abnormal security",
  "accenture",
  "accolade",
  "acerta pharma",
  "aci worldwide",
  "acorns",
  "actifio",
  "activecampaign",
  "activision",
  "acv auctions",
  "adaptive biotechnologies",
  "adepar",
  "adobe",
  "adp",
  "advanced micro devices, inc.",
  "advizr",
  "adyen",
  "affirm",
  "age of learning",
  "agero",
  "aha",
  "aha!",
  "airbnb",
  "airtable",
  "airwallex",
  "akamai",
  "akuna capital",
  "alarm.com",
  "aledade",
  "alibaba",
  "alkami",
  "allbirds",
  "allen institute",
  "allscripts",
  "allstate",
  "ally",
  "alphabet",
  "altair",
  "alteryx",
  "alto pharmacy",
  "alyce",
  "alzheon",
  "amazon",
  "amazon web services",
  "amazon.com",
  "amd",
  "american airlines",
  "american express",
  "american family insurance",
  "amex",
  "amgen",
  "amplitude",
  "analog devices",
  "anaplan",
  "ancestry",
  "anduril",
  "ansys",
  "apeel sciences",
  "apollo graphql",
  "appdirect",
  "appdynamics",
  "appen",
  "appfolio",
  "appian",
  "applause",
  "apple",
  "applied intuition",
  "applovin",
  "appnexus",
  "appsflyer",
  "apptio",
  "apsilon",
  "apttus",
  "argo ai",
  "arista",
  "arity",
  "armis",
  "artic wolf networks",
  "aruba",
  "asana",
  "asml",
  "assetz capital",
  "asurion",
  "at&t",
  "athenahealth",
  "atlassian",
  "atom",
  "attachmate group",
  "attentive",
  "auction.com",
  "audible",
  "aurora",
  "auth0",
  "autodesk",
  "automation anywhere",
  "automattic",
  "autonomic",
  "auxmoney",
  "avant",
  "avantcredit",
  "avature",
  "avaya",
  "avidxchange",
  "avigilon",
  "away",
  "aws",
  "axiom space",
  "axonius",
  "aza group",
  "azimo",
  "balyasny",
  "bamboohr",
  "bank of america",
  "barclays",
  "bcg digital ventures",
  "beeswax",
  "belvedere trading",
  "benchling",
  "benchlings",
  "bentley",
  "bento for business",
  "better",
  "better.com",
  "betterment",
  "betterup",
  "bigcommerce",
  "bigid",
  "bill",
  "bill.com",
  "billtrust",
  "bird rides",
  "bitpesa",
  "bitsight",
  "bitstamp",
  "blackbaud",
  "blackboard",
  "blackline",
  "blackrock",
  "blackstone",
  "blend",
  "blizzard",
  "blockfi",
  "bloom energy",
  "bloomberg",
  "blue apron",
  "blue yonder",
  "bluevine",
  "bmc",
  "bnp paribas",
  "bny mellon",
  "board",
  "bond street",
  "bondora",
  "boom supersonic",
  "bosch",
  "bought by many",
  "box",
  "box.com",
  "braintree",
  "branch",
  "braviant holdings",
  "braze",
  "brex",
  "bright healthcare",
  "brightinsight",
  "brooklinen",
  "bruva",
  "btc media",
  "buffer",
  "bungalow",
  "buzzfeed",
  "bytedance",
  "c2fo",
  "c3 ai",
  "c3.ai",
  "ca",
  "cadance",
  "calendly",
  "calm",
  "cambridge mobile telematics",
  "cameo",
  "candence design",
  "canoo",
  "canva",
  "capital group",
  "capital one",
  "capsule",
  "carbon",
  "carbon black",
  "carbon health",
  "carbon3d",
  "care.com",
  "cargurus",
  "carmax",
  "carta",
  "castlight",
  "cb insights",
  "cbre",
  "ccc",
  "ccc information",
  "cdw",
  "cedar",
  "celonis",
  "census",
  "centrify",
  "centro",
  "cerebras",
  "cerner",
  "certain lending",
  "chainalysis",
  "charles river",
  "charles schwab",
  "charthop",
  "chase pay",
  "checkout.com",
  "checkr",
  "chewy",
  "chicago trading",
  "chief",
  "chime",
  "circle",
  "circle internet",
  "cisco",
  "citadel",
  "citi",
  "citrix",
  "cityblock health",
  "civitas learning",
  "clari",
  "classpass",
  "clearbit",
  "clearcover",
  "clever",
  "clickup",
  "climate corporation",
  "close",
  "close.io",
  "cloudbeds",
  "cloudera",
  "cloudflare",
  "cloudinary",
  "cloudstrike",
  "clubhouse",
  "coalition",
  "cockroach labs",
  "cocoon",
  "coda",
  "codesandbox",
  "cohesity",
  "coinbase",
  "collage.com",
  "collective health",
  "collibra",
  "color",
  "comcast",
  "commonbond",
  "commvault",
  "compass",
  "concur",
  "confluent",
  "conga",
  "constellation",
  "convene",
  "convergys",
  "convoy",
  "cornerstone",
  "coupa",
  "coupang",
  "course hero",
  "coursera",
  "creatio",
  "credit karma",
  "credit suisse",
  "crouchbase",
  "crowdcube",
  "crowdfunder",
  "crowdstrike",
  "cruise",
  "culture amp",
  "curative",
  "curriculum associates",
  "curriculum asssociates",
  "cuvva",
  "cvent",
  "cybereason",
  "cybergrx",
  "cylance",
  "cylynt",
  "d.e. shaw",
  "darktrace",
  "dassault",
  "databricks",
  "datadog",
  "dataiku",
  "dataminr",
  "datarobot",
  "datastax",
  "datev",
  "datorama",
  "datto",
  "dave",
  "deem",
  "deliverr",
  "dell",
  "deutsche",
  "devoted health",
  "dfin",
  "dialogtech",
  "digital asset",
  "digital ocean",
  "digitalglobe",
  "digitalocean",
  "digitate",
  "disco",
  "discord",
  "discoverorg",
  "discovery digital",
  "disney",
  "dispatchhealth",
  "divvy",
  "docker",
  "docusign",
  "dolby",
  "doloitte",
  "domino data",
  "domo",
  "doordash",
  "draftkings",
  "dremio",
  "drift",
  "dropbox",
  "druva",
  "drw",
  "dtcc",
  "duck creek",
  "duolingo",
  "dutchie",
  "dwolla",
  "dynatrace",
  "e*trade",
  "e-trade",
  "ebay",
  "edx",
  "egnyte",
  "eightfold",
  "eightfold.ai",
  "elastic",
  "elastic.co",
  "electronic arts",
  "embark trucks",
  "emc",
  "enfusion",
  "enlitic",
  "enova",
  "eog",
  "epic",
  "epic games",
  "epic systems",
  "epicor",
  "eset",
  "esri",
  "ethereum",
  "etrade",
  "etsy",
  "eventbrite",
  "everbridge",
  "everlywell",
  "evernote",
  "expedia",
  "ezcater",
  "f5 networks",
  "facebook",
  "factset",
  "factual",
  "fair",
  "fair dialpad",
  "faire",
  "fanatics",
  "fanduel",
  "fannie mae",
  "farmers business network",
  "fast enterprises",
  "fastly",
  "fico",
  "fig",
  "figma",
  "figure",
  "finix",
  "fis",
  "fiserv",
  "fishtown analytics",
  "fitsense",
  "five rings",
  "five9",
  "fivetran",
  "flatiron",
  "flexport",
  "flipboard",
  "flockjay",
  "flywire",
  "formlabs",
  "forter",
  "fortinet",
  "fortressiq",
  "forward financing",
  "freshworks",
  "friendsurance",
  "front",
  "fujitsu",
  "fullcontact",
  "fullstory",
  "fulutterwave",
  "funding circle",
  "fundrise",
  "fuse",
  "fuze",
  "gainsight",
  "gap",
  "gatsby",
  "ge healthcare",
  "genentech",
  "general eletric",
  "genesys",
  "genesys telecommunications",
  "gfi",
  "ginkgo bioworks",
  "github",
  "gitlab",
  "globality",
  "glossier",
  "goat",
  "godaddy",
  "goldman sachs",
  "gong",
  "gong.io",
  "good technology",
  "google",
  "gopro",
  "gopuff",
  "gospotcheck",
  "grafana",
  "grammarly",
  "gravity payments",
  "greenlight",
  "greensky",
  "groupon",
  "grove collaborative",
  "grubhub",
  "guaranteed rate",
  "guidewire",
  "guild education",
  "gusto",
  "gympass",
  "habito",
  "harness",
  "harry's razor",
  "hashicorp",
  "hawke media",
  "hbo",
  "heartflow",
  "hellofresh",
  "hewlett packard",
  "hewlett-packard",
  "hexagon",
  "highradius",
  "highspot",
  "hinge health",
  "hitachi",
  "homeadvisor",
  "homeaway",
  "honest",
  "honest co.",
  "honey",
  "hotjar",
  "houzz",
  "hp",
  "hubspot",
  "hudson river",
  "hulu",
  "hydrogen",
  "ibm",
  "ibotta",
  "icertis",
  "icims",
  "ihs markit",
  "ike",
  "illumio",
  "imc",
  "imedx",
  "impossible foods",
  "incertis",
  "indeed",
  "indigo ag",
  "infinidat",
  "infor",
  "informatica",
  "inmobi",
  "innovaccer",
  "innovium",
  "insidesales",
  "instabase",
  "instacart",
  "intarcia therapeutics",
  "intel",
  "interactive brokers",
  "intercom",
  "intersystems",
  "intralinks",
  "intuit",
  "intuitive surgical",
  "invalua",
  "invision",
  "ironclad",
  "isn",
  "iterable",
  "izettle",
  "jane street",
  "jasper",
  "jawbone",
  "jda",
  "jefferies",
  "jet",
  "jfrog",
  "jobot",
  "jpmorgan",
  "jpmorgan chase",
  "jump trading",
  "just",
  "justfab",
  "justworks",
  "juul",
  "k health",
  "kabam",
  "kabbage",
  "kareo",
  "kaseya",
  "kasko",
  "kaspersky",
  "katerra",
  "keep truckin",
  "keeptruckin",
  "kendra scott",
  "kenna security",
  "khan academy",
  "kkw beauty",
  "kla",
  "klarna",
  "klaviyo",
  "knip",
  "knowbe4",
  "kong",
  "kraken",
  "kronos",
  "kyriba",
  "lacework",
  "lam research",
  "lattice",
  "launchdarkly",
  "legalzoom",
  "legendary entertainment",
  "leidos",
  "lemonade",
  "lending club",
  "lendingclub",
  "lendinvest",
  "lendio",
  "lendup",
  "leo",
  "lifion",
  "lime",
  "limeade",
  "linear",
  "linkedin",
  "liquid web",
  "liveperson",
  "lob",
  "locus robotics",
  "logdna",
  "looker",
  "lookout",
  "loom",
  "lord abbett",
  "lower",
  "lu.com",
  "lucid",
  "lumentum",
  "lyell immunopharma",
  "lyft",
  "lynda",
  "lyra",
  "lytx",
  "machine zone",
  "magic leap",
  "magic software",
  "magicleap",
  "mailchimp",
  "market axess",
  "market finance",
  "marklogic",
  "marqeta",
  "marqueta",
  "mastercard",
  "masterclass",
  "match",
  "mathworks",
  "mckesson",
  "medallia",
  "mediamath",
  "medidata",
  "meditech",
  "medtouch",
  "mendix",
  "mentor graphics",
  "meundies",
  "micro focus",
  "micros",
  "microsoft",
  "microstrategy",
  "millennium management",
  "mindstrong",
  "mint",
  "miro",
  "misys",
  "mitchell international",
  "mitek",
  "modern health",
  "modern treasury",
  "modern tribe",
  "moderna therapeutics",
  "modernizing medicine",
  "monday.com",
  "moneyfarm",
  "mongodb",
  "monte carlo",
  "monzo",
  "moogsoft",
  "moonshot factory",
  "morgan stanley",
  "morningstar",
  "motorola",
  "moveon",
  "mozido",
  "mu sigma",
  "mufg",
  "mulesoft",
  "mx",
  "n26",
  "namely",
  "nanthealth",
  "navex global",
  "ncr",
  "nec",
  "neo4j",
  "nerdwallet",
  "netapp",
  "netdoor",
  "netflix",
  "netlify",
  "netskope",
  "netspend",
  "netsuite",
  "neusoft",
  "new engen",
  "new relic",
  "new york times",
  "newsela",
  "next insurance",
  "nextdoor",
  "nextiva",
  "niantic",
  "nice",
  "nielseniq",
  "nintex",
  "njoy",
  "nokia",
  "nomura",
  "noom",
  "nordstrom",
  "nortonlifelock",
  "notion",
  "notion labs",
  "ntwrk",
  "nuance communications",
  "nuro",
  "nutanix",
  "nutmeg",
  "nuvia",
  "nvidia",
  "o9 solutions",
  "ochard",
  "odoo",
  "okta",
  "olive",
  "on24",
  "ondeck",
  "one medical",
  "onetrust",
  "open networking foundation",
  "openai",
  "opendoor",
  "opengov",
  "openmarket",
  "opentable",
  "opentext",
  "openx",
  "oportun",
  "opploans",
  "optimizely",
  "optiver",
  "optum",
  "oracle",
  "orca bio",
  "orchard",
  "oscar",
  "oscar health",
  "oscar health insurance",
  "osisoft",
  "outreach",
  "outsystems",
  "ownbackup",
  "p.volve",
  "pagerduty",
  "palantir",
  "palo alto networks",
  "pandora",
  "panther labs",
  "papaya global",
  "partnercentric",
  "pat mcgrath",
  "patientpop",
  "patreon",
  "pax",
  "paycom",
  "paydiant",
  "payformance solutions",
  "paylocity",
  "paypal",
  "payscale",
  "pegasystems",
  "peloton",
  "pendo",
  "peopledoc",
  "personal capital",
  "pharmapacks",
  "pindrop security",
  "pinterest",
  "pipedrive",
  "pitchbook",
  "pitney bowes",
  "pivotal software",
  "plaid",
  "planet labs",
  "plangrid",
  "playstation",
  "plume",
  "pluralsight",
  "pocket gems",
  "podium",
  "pony ai",
  "pony.ai",
  "postman",
  "postmates",
  "powertofly",
  "priceline",
  "privacera",
  "pro.com",
  "procore",
  "prodege",
  "productboard",
  "proofpoint",
  "prosper marketplace",
  "proteus digital",
  "prudential",
  "ptc",
  "public.com",
  "pulse secure",
  "pure storage",
  "pvolve",
  "qad",
  "qlik",
  "qualcomm",
  "qualia",
  "qualtrics",
  "qualys",
  "quanergy",
  "quantcast",
  "quantum metric",
  "quibi",
  "quickbase",
  "quizlet",
  "qumulo",
  "quora",
  "radiology partners",
  "rally health",
  "rani therapeutics",
  "rapid7",
  "ratesetter",
  "raytheon",
  "razer",
  "red hat",
  "red ventures",
  "reddit",
  "redfin",
  "redis labs",
  "reef",
  "relativity",
  "relativity space",
  "remitly",
  "rent the runway",
  "repl.it",
  "retailmenot",
  "retool",
  "return path",
  "rex homes",
  "ridgeline",
  "ringcentral",
  "riot games",
  "ripple",
  "ripple xpring",
  "rippling",
  "riskified",
  "rivian",
  "ro",
  "roam research",
  "robinhood",
  "roblox",
  "roivant sciences",
  "roku",
  "roost",
  "rubicon global",
  "rubrik",
  "sage",
  "sage bionetworks",
  "sailpoint",
  "salesforce",
  "salesforce.com",
  "salesloft",
  "samsara",
  "samsara networks",
  "samsung",
  "samumed",
  "sana benefits",
  "sap",
  "sap america",
  "sas",
  "sas institute",
  "savage x fenty",
  "scalable capital",
  "scale ai",
  "schneider electric",
  "schonfeld",
  "schoology",
  "sciencelogic",
  "scopely",
  "scribd",
  "seamless.ai",
  "seatgeek",
  "securelink",
  "seedrs",
  "segment",
  "seismic",
  "sendoso",
  "sentinelone",
  "sentry",
  "servicenow",
  "servicetitan",
  "shazam",
  "shift",
  "shopify",
  "shopkeep",
  "shutterfly",
  "shyft analytics",
  "sidecar health",
  "siements",
  "sig",
  "sigfig",
  "sigma computing",
  "sila nanotechnologies",
  "similarweb",
  "simplivity",
  "simplrflex",
  "sisense",
  "siteimprove",
  "sketch",
  "skillz",
  "skydance",
  "skydio",
  "slack",
  "slice labs",
  "smartbear",
  "smartsheet",
  "sms assist",
  "snap",
  "snapchat",
  "snaplogic",
  "snorkel ai",
  "snowflake",
  "snyk",
  "social finance",
  "social solutions",
  "socialbakers",
  "socotra",
  "socure",
  "sofi",
  "software ag",
  "solarwinds",
  "sonder",
  "sony",
  "soundhound",
  "spacex",
  "splashtop",
  "splunk",
  "spotify",
  "sprinklr",
  "square",
  "squarepoint",
  "squarespace",
  "standard cognition",
  "starburst",
  "starling bank",
  "starry",
  "steelhouse",
  "stemcentrx",
  "steppie",
  "stockx",
  "strava",
  "stripe",
  "stryker",
  "substack",
  "sumo logic",
  "sumologic",
  "sungard",
  "sunrun",
  "superhuman",
  "suplari",
  "surveymonkey",
  "sweetgreen",
  "swift",
  "symantec",
  "symphony",
  "symphony communication services",
  "synaptics",
  "synopsys",
  "tableau",
  "tala",
  "talentica",
  "talkdesk",
  "tandem",
  "tango",
  "tangome",
  "tanium",
  "tapad",
  "td securities",
  "tealium",
  "teambrella",
  "techstyle fashion group",
  "tekion",
  "tempus",
  "teradata",
  "tesla",
  "the hartford",
  "theranos",
  "thomson reuters",
  "thoughtspot",
  "thoughtworks",
  "thrasio",
  "thumbtack",
  "tibco",
  "tide",
  "tiktok",
  "tinder",
  "tipalti",
  "toast",
  "totvs",
  "trade desk",
  "tradeshift",
  "tradeweb",
  "transferwise",
  "transparent",
  "transunion",
  "trella",
  "trend micro",
  "tresata",
  "tripactions",
  "tripadvisor",
  "trueaccord",
  "trumid",
  "trustwave",
  "tsuru capital",
  "tula skincare",
  "tusimple",
  "twilio",
  "twitch",
  "twitter",
  "two sigma",
  "uber",
  "udacity",
  "udemy",
  "uipath",
  "ukg",
  "ultimate kronos group",
  "ultimate software",
  "unacast",
  "unit4",
  "unite us",
  "united airlines",
  "unitedhealth",
  "unity",
  "unqork",
  "upgrade",
  "upkey",
  "uplight",
  "uptake",
  "upwork",
  "uship",
  "ust global",
  "vacasa",
  "vanguard",
  "varo money",
  "vast data",
  "veeam",
  "veeva",
  "venafi",
  "venmo",
  "vercel",
  "verifi",
  "verily life sciences",
  "verint",
  "veritas",
  "verizon",
  "verkada",
  "vertafore",
  "via transportation",
  "viasat",
  "vice",
  "villagemd",
  "virta",
  "virtu financial",
  "visa",
  "visma",
  "vistaprint",
  "vmware",
  "volley",
  "voloen",
  "vox",
  "vrbo",
  "vts",
  "walkme",
  "walmart",
  "walmart labs",
  "walt disney",
  "warby parker",
  "warnermedia",
  "washington post",
  "wayfair",
  "waymo",
  "wealthfront",
  "wealthsimple",
  "weave",
  "webflow",
  "webroot",
  "weee!",
  "wells fargo",
  "wepay",
  "western asset",
  "wework",
  "whoop",
  "wincor nixdorf",
  "wish",
  "wolters kluwer",
  "wolverine trading",
  "wonolo",
  "workato",
  "workday",
  "workfront",
  "workiva",
  "workrise",
  "world wide",
  "worldpay",
  "worldremit",
  "wp engine",
  "ww",
  "wwt",
  "xactly",
  "xant",
  "xoom",
  "yahoo",
  "yapstone",
  "yardi",
  "yelp",
  "yext",
  "yotpo",
  "you & mr jones",
  "younited credit",
  "zaloni",
  "zapier",
  "zayo",
  "zebra",
  "zendesk",
  "zenefits",
  "zenoti",
  "zestfinace",
  "zeta global",
  "zeta interactive",
  "zillow",
  "zipline",
  "ziprecruiter",
  "zocdoc",
  "zoho",
  "zoom",
  "zoominfo",
  "zoox",
  "zscaler",
  "zulily",
  "zume",
  "zuora",
  "zwift",
  "zymergen",
  "zynga",
];

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

const others = [
  "09",
  "1041 games",
  "1password",
  "2u",
  "abee",
  "abl space systems",
  "acompli",
  "acronis",
  "active campaign",
  "ada",
  "adap.tv",
  "addepar",
  "addi",
  "advance",
  "advance intelligence",
  "afiniti",
  "agicap",
  "agile robots",
  "aircall",
  "airmeet",
  "alan",
  "alation",
  "albert",
  "alchemy",
  "algolia",
  "alloy",
  "alma",
  "alphasense",
  "altana ai",
  "alto",
  "amber",
  "amerity",
  "amount",
  "anchorage digital",
  "andros",
  "answers.com",
  "anvyl",
  "applyboard",
  "appzen",
  "aprogen",
  "apus",
  "aqua",
  "argo",
  "arrail",
  "artic wolf",
  "articulate",
  "arturo",
  "asapp",
  "ascend money",
  "ask",
  "asr",
  "astero",
  "atbay",
  "auditude",
  "aura",
  "autobooks",
  "aviatnx",
  "avnera",
  "axtria",
  "babylon",
  "back market",
  "balance",
  "balanced",
  "bedrock",
  "beisen",
  "belvo",
  "bench",
  "benevolent",
  "bestow",
  "betterbank",
  "bharatpe",
  "bigo",
  "bioage",
  "biosplice",
  "bitcoin suisse",
  "bitfury",
  "bitgo",
  "bitmain",
  "bitpanda",
  "bitso",
  "bitsos",
  "bitwise",
  "blablacar",
  "black crow",
  "black sesame",
  "black unicorn factory",
  "blackbuck",
  "blockchain.com",
  "blockdaemon",
  "bluecore",
  "bluefin labs",
  "bluekai",
  "bodhala",
  "bolt",
  "bolttech",
  "boom",
  "bordrin",
  "borrowell",
  "boughtbymany",
  "bowery",
  "bravado",
  "bravely",
  "brewdog",
  "bright health",
  "brightflag",
  "brighthire",
  "brigit",
  "bringg",
  "browserstack",
  "bulletin",
  "bunq",
  "button",
  "byju's",
  "byton",
  "c3 iot",
  "c6bank",
  "cabify",
  "caocao",
  "capitalize",
  "capitolis",
  "carbon 3d",
  "caris",
  "carousell",
  "carro",
  "cars24",
  "carsome",
  "carson",
  "carzone",
  "cascade",
  "cashfree",
  "caspida",
  "catalyst",
  "cato",
  "cava",
  "ceckout.com",
  "cellc",
  "celo",
  "cerebral",
  "certik",
  "chargebee",
  "check",
  "chinac",
  "chipper",
  "choosy",
  "chorus",
  "chronosphere",
  "cider",
  "circleci",
  "cityblock",
  "claroty",
  "cleancult",
  "clear",
  "clearco",
  "clearwell",
  "clicker",
  "clio",
  "clip",
  "cloud.com",
  "cloudsimple",
  "cloudwalk",
  "clover",
  "cmr",
  "codat",
  "coder",
  "coedition",
  "coflow",
  "cognite",
  "coindcx",
  "commure",
  "comply advantage",
  "content square",
  "contentfull",
  "coocaa",
  "cooks venture",
  "copado",
  "copper.co",
  "corvus",
  "course heor",
  "coveo",
  "cowbell cyber",
  "cred",
  "credit sesame",
  "creditas",
  "cribl",
  "cross river",
  "crossbeam",
  "cultur amp",
  "current",
  "cybercube",
  "cylera",
  "cypris",
  "cyral",
  "daily harvest",
  "dailyhunt",
  "dailypay",
  "dandy",
  "danger",
  "dapper",
  "dbt",
  "deel",
  "deezer",
  "degreed",
  "delhivery",
  "deliverect",
  "descript",
  "deserve",
  "desktop metal",
  "dialpad",
  "diamond foundry",
  "digit",
  "dispatch health",
  "distrokid",
  "divide",
  "dji",
  "doctolil",
  "dream",
  "dream11",
  "drivenets",
  "drivewealth",
  "dunamu",
  "dune analytics",
  "duo",
  "earnix",
  "easyhome",
  "ebanx",
  "ebureau",
  "ecarx",
  "eero",
  "efficient frontier",
  "embroker",
  "empg",
  "enfuce",
  "ephemeral",
  "epidemic sound",
  "eq",
  "equitybee",
  "eruditus",
  "ethos",
  "ethyca",
  "everywell",
  "evidation",
  "exabeam",
  "extend",
  "fable",
  "fabric",
  "fairmarkit",
  "falconx",
  "fazzfinancial",
  "feather",
  "feedzai",
  "fetch",
  "finoa",
  "finxact",
  "fireblocks",
  "fireblocks,firedome",
  "firefly",
  "firstcry",
  "firstleaf",
  "fiture",
  "fivestar",
  "flash",
  "flexe",
  "flixbus",
  "flock",
  "floqast",
  "flowcode",
  "flume health",
  "flutterwave",
  "flyhomes",
  "flymachine",
  "fondeadora",
  "forte",
  "forto",
  "freo",
  "freshbooks",
  "frotinet",
  "ftx",
  "galaxy digital",
  "galileo",
  "geek",
  "gelato",
  "gem",
  "gemini",
  "generation transfer",
  "genesis",
  "get your guide",
  "getaway",
  "getir",
  "gett",
  "gigster",
  "glia",
  "global switch",
  "glovo",
  "go1",
  "gocardless",
  "gostudent",
  "gousto",
  "grab",
  "grafana labs",
  "graphcore",
  "gravity",
  "gravy",
  "great jones",
  "greenwood",
  "gremlin",
  "grofers",
  "groq",
  "groww",
  "guide",
  "guideline",
  "guild",
  "gupshup",
  "gymshark",
  "hailo",
  "hammerhead",
  "handshake",
  "harry's",
  "hash",
  "hayden",
  "healthify",
  "heartbeat health",
  "height",
  "helaina",
  "hello tabitha",
  "hello transtech",
  "heroku",
  "hesai",
  "heytea",
  "himarley",
  "hims",
  "hiradius",
  "hive",
  "hlth",
  "hmbradley",
  "hmd",
  "homeis",
  "homelight",
  "hometap",
  "honeybook",
  "hop.in",
  "hopper",
  "hotmart",
  "howden group",
  "huaqin",
  "human interest",
  "human longevity",
  "humanified",
  "hyalroute",
  "hydrant",
  "hyperscience",
  "icapital",
  "icarbonx",
  "id.me",
  "ifeed",
  "immobi",
  "immuta",
  "impact",
  "impact radius",
  "impossible",
  "improbable",
  "inari",
  "incloudcounsel",
  "indigo",
  "infobip",
  "infra market",
  "injective protocol",
  "insidesales.com",
  "insightec",
  "intarcia",
  "intellifusion",
  "intent",
  "internet brands",
  "interos",
  "irl",
  "itutorgroup",
  "j&t express",
  "jerry",
  "jetsmarer",
  "jimu",
  "jollychic",
  "joytunes",
  "judobank",
  "jumpcloud",
  "juniper networks",
  "juniper square",
  "just eat",
  "kajabi",
  "kangaroo",
  "kavak",
  "kazeon",
  "keep",
  "khatabook",
  "kindred",
  "kinetic",
  "kitopi",
  "klook",
  "knowbox",
  "kodiak networks",
  "komodo",
  "kry",
  "kurly",
  "kustomer",
  "l&p cosmetic",
  "ladder",
  "lalamove",
  "lantern",
  "lastline",
  "latch",
  "leap",
  "leapmotor",
  "leaselock",
  "ledger",
  "lenskart",
  "lets get checked",
  "lex markets",
  "lifemiles",
  "lifesize",
  "lightbricks",
  "lightstep",
  "lili",
  "lilt",
  "linkdoc",
  "linksure",
  "liquid",
  "lithic",
  "lively",
  "livepeer",
  "loft",
  "loggi",
  "logixboard",
  "loopnet",
  "luchbox",
  "lukka",
  "luko",
  "luminary media",
  "lunar",
  "lyra health",
  "m1 finace",
  "madeira madeira",
  "mafengwo",
  "makespace",
  "mambu",
  "mammoth biosiences",
  "mano mano",
  "mantl",
  "maple",
  "marshmalow",
  "materialize",
  "matillion",
  "matrixport",
  "mattermost",
  "maven",
  "medable",
  "meero",
  "meesho",
  "megvii",
  "meizu",
  "melio",
  "mercury",
  "messagebird",
  "messari",
  "mikmak",
  "mindmaze",
  "mindtickle",
  "mirakl",
  "mirror",
  "misfits market",
  "mission lane",
  "mixlab",
  "mobilecoin",
  "mobot",
  "mobvoi",
  "moderna",
  "modulr",
  "mofang",
  "moglix",
  "mollie",
  "moloco",
  "morning consult",
  "moveworks",
  "movile",
  "mpl",
  "musinsa",
  "mux",
  "myspace",
  "mywellbeing",
  "nanopore",
  "narmi",
  "nearby",
  "neuralink",
  "news break",
  "nexii",
  "next",
  "next silicon",
  "nexthink",
  "ninjavan",
  "nium",
  "northone",
  "northvolt",
  "notarize",
  "nova credit",
  "nova fitness",
  "novat",
  "nse",
  "nu",
  "nubank",
  "numbrs",
  "nuvemship",
  "nykaa",
  "nymbus",
  "oaknorth",
  "ocrolus",
  "odeko",
  "ofbusiness",
  "offchain labs",
  "offerup",
  "ola",
  "ola electric",
  "ollie",
  "omio",
  "one three biotech",
  "one97",
  "onfido",
  "opay",
  "open english",
  "opensea",
  "opentrons",
  "opsani",
  "orbbec",
  "orca security",
  "orcabio",
  "orcam",
  "orillas",
  "orum",
  "ottoblock",
  "outcome health",
  "outdoor voices",
  "outschool",
  "ouyeel",
  "overtime",
  "ovh cloud",
  "ovo",
  "own backup",
  "owner",
  "oyo",
  "pacaso",
  "packagefree",
  "pagaya",
  "pair eyewear",
  "pandadoc",
  "pantheon",
  "papa & barkley",
  "papayaglobal",
  "paradigm",
  "patsnap",
  "pattern",
  "pave",
  "pawlicy advisor",
  "paxos",
  "paycargo",
  "payfit",
  "paymongo",
  "paysend",
  "paystand",
  "pbizon",
  "peel",
  "pennylane",
  "people.ai",
  "perry",
  "persona",
  "personio",
  "petal",
  "phenom",
  "picsart",
  "pie insurance",
  "pilot",
  "pine labs",
  "pinelabs",
  "pinwheel",
  "pipe",
  "planet",
  "platform9",
  "pleo",
  "plural",
  "pointclickcare",
  "policy bazaar",
  "policygenius",
  "poni.ai",
  "posterous spaces",
  "ppro",
  "preferred networks",
  "preset",
  "primarybid",
  "prime medicine",
  "printful",
  "project 44",
  "prosper",
  "proterra",
  "proteus",
  "psiquantum",
  "pumpaudio",
  "qonto",
  "qualified",
  "quantexa",
  "queerly health",
  "quinto andar",
  "quintoandar",
  "radius",
  "railsbank",
  "rally",
  "rappi",
  "rapyd",
  "razorpay",
  "real",
  "realblocks",
  "realm",
  "rebellion",
  "recharge",
  "redwood materials",
  "reify health",
  "relateiq",
  "relay",
  "remote",
  "reonomy",
  "reserve trust",
  "responsys",
  "revel",
  "revolut",
  "rhino",
  "rightmedia",
  "rightway",
  "ritual",
  "rivigo",
  "rocean",
  "rocket lab",
  "rohlik",
  "roivant",
  "roofstock",
  "root",
  "routehappy",
  "royole",
  "rubicon",
  "runway",
  "safety culture",
  "saltpay",
  "sambanova",
  "saysh",
  "scalable",
  "scalable capatal",
  "seated",
  "selfmade",
  "sendbird",
  "sennder",
  "sense",
  "sentinel one",
  "service titan",
  "settle",
  "sharechat",
  "shield ai",
  "shien",
  "shipbob",
  "shippo",
  "showfields",
  "side",
  "sidecare health",
  "sift",
  "signifyd",
  "sila",
  "silk sonder",
  "simplenexus",
  "simpo",
  "skims",
  "slice",
  "small door",
  "smart recuriters",
  "smartasset",
  "smarthr",
  "smartmore",
  "smartnews",
  "snapdeal",
  "snapdocks",
  "snapdocs",
  "snappy",
  "snorkel",
  "socar",
  "solarisbank",
  "solo.io",
  "songtradr",
  "sonos",
  "sorare",
  "soundmind",
  "sourcegraph",
  "spark",
  "speak it yourself",
  "spiber",
  "spoton",
  "spring health",
  "springhill",
  "springpath",
  "spruce",
  "squarefoot",
  "ssense",
  "stackrox",
  "stampli",
  "standard",
  "star charge",
  "stash",
  "stashaway",
  "stellar health",
  "step",
  "stoop",
  "stord",
  "storsimple",
  "strive health",
  "stx entertainment",
  "summer",
  "sumup",
  "sunbit",
  "supergreat",
  "surgarai",
  "svolt",
  "swiggy",
  "synthetix",
  "sysdig",
  "tact.ai",
  "talkingdata",
  "tantalus",
  "taskade",
  "tastemade",
  "taxbit",
  "techstyle",
  "ten x",
  "tend",
  "tenor",
  "tenstorrent",
  "terminus",
  "tgi",
  "the clear cut",
  "the zebra",
  "therabody",
  "thimble",
  "thredup",
  "thunes",
  "ticketfly",
  "timescale",
  "titan",
  "tivo",
  "tomorrow health",
  "tonal",
  "toss",
  "tractable",
  "trade republic",
  "trader interactive",
  "transform",
  "transmit security",
  "traveloka",
  "trax",
  "treasury prime",
  "trip.com",
  "truebill",
  "truelayer",
  "truework",
  "truex media",
  "trulioo",
  "trusignal",
  "trust will",
  "tundra",
  "txvia",
  "uala",
  "ubtech",
  "uisee",
  "unacademy",
  "unico",
  "unit",
  "united imaging",
  "upfront",
  "upgrad",
  "urban company",
  "valon",
  "vancl",
  "variance",
  "varo",
  "vast",
  "vectra",
  "veepee",
  "vendry",
  "venn",
  "verbit",
  "vestlaire collective",
  "vestwell",
  "via",
  "viajanet",
  "village md",
  "vinted",
  "vip kid",
  "virtual facility",
  "vise",
  "visier",
  "vista global",
  "voodoo",
  "vouch",
  "vox media",
  "vurb",
  "wave",
  "webull",
  "wefox",
  "welab",
  "welcome",
  "weride",
  "whatnot",
  "whosay",
  "wichorus",
  "wildlife",
  "wiz",
  "wochit",
  "wtiop",
  "wunderkind",
  "wyre",
  "xendit",
  "xfers",
  "xlris",
  "xmtp",
  "xtalpi",
  "yanolja",
  "yello mobile",
  "yieldstreet",
  "yipit data",
  "yitu",
  "ymglobal",
  "youth to the people",
  "youxia",
  "zego",
  "zenlytic",
  "zepz",
  "zeta",
  "zetwerk",
  "zimbra",
  "ziroom",
  "zong",
];

companies.push.apply(companies, others);

/*
Python script to add companies from newString: 
newString = ""
arr = newString.split(", ")
print(sorted(list(set(companies + arr))))

Note: 
=> companies array includes software companies, tech companies, fintech companies, startups, and unicorns
To optimize the array:
=> verify all .name companies (.com, .ai, .io, .co, inc., co.)
=> trim names of companies whose names are longer than 3 words, if applicable
=> remove the words technology/technologies/company/corporation/incorporated/systems/software/financial/media/services/labs/health
   from company names, if applicable
*/

exports.companies = companies;
