const companies = [
  "10up",
  "23andme",
  "a cloud guru",
  "a10 networks",
  "accolade",
  "acerta pharma",
  "aci worldwide",
  "acorns",
  "actifio",
  "activecampaign",
  "activision",
  "acv auctions",
  "adaptive biotechnologies",
  "adepar",
  "adobe",
  "adp",
  "advizr",
  "adyen",
  "affirm",
  "age of learning",
  "agero",
  "aha",
  "aha!",
  "airbnb",
  "airtable",
  "airwallex",
  "akamai",
  "aledade",
  "alkami",
  "alkami technology",
  "allbirds",
  "allscripts",
  "allstate",
  "ally financial",
  "alphabet",
  "altair",
  "alteryx",
  "alto pharmacy",
  "alyce",
  "alzheon",
  "amazon",
  "amazon web services",
  "amazon.com",
  "amplitude",
  "anaplan",
  "anduril",
  "ansys",
  "apeel sciences",
  "appdirect",
  "appdynamics",
  "appen",
  "appfolio",
  "applause",
  "apple",
  "applied intuition",
  "applovin",
  "appnexus",
  "appsflyer",
  "apptio",
  "apsilon",
  "apttus",
  "argo ai",
  "armis",
  "artic wolf networks",
  "asana",
  "assetz capital",
  "asurion",
  "athenahealth",
  "atlassian",
  "atom",
  "attentive",
  "auction.com",
  "aurora",
  "auth0",
  "autodesk",
  "automation anywhere",
  "automattic",
  "auxmoney",
  "avant",
  "avantcredit",
  "avature",
  "avaya",
  "avidxchange",
  "away",
  "aws",
  "axiom space",
  "axonius",
  "aza group",
  "azimo",
  "bamboohr",
  "bcg digital ventures",
  "beeswax",
  "benchling",
  "bentley",
  "bento for business",
  "better",
  "better.com",
  "betterment",
  "betterup",
  "bigcommerce",
  "bigid",
  "bill",
  "bill.com",
  "billtrust",
  "bird rides",
  "bitpesa",
  "bitsight",
  "bitstamp",
  "blackbaud",
  "blackboard",
  "blackline",
  "blend",
  "blockfi",
  "bloom energy",
  "bloomberg",
  "blue apron",
  "blue yonder",
  "bluevine",
  "bmc",
  "board",
  "bond street",
  "bondora",
  "boom supersonic",
  "bought by many",
  "box",
  "box.com",
  "braintree",
  "branch",
  "braviant holdings",
  "braze",
  "brex",
  "bright healthcare",
  "brightinsight",
  "brooklinen",
  "bruva",
  "btc media",
  "buffer",
  "bungalow",
  "buzzfeed",
  "c2fo",
  "c3 ai",
  "c3.ai",
  "ca technologies",
  "calendly",
  "calm",
  "cambridge mobile telematics",
  "cameo",
  "candence design",
  "canva",
  "capital one",
  "capsule",
  "carbon",
  "carbon black",
  "carbon health",
  "carbon3d",
  "care.com",
  "cargurus",
  "carta",
  "cb insights",
  "ccc",
  "ccc information",
  "cdw",
  "cedar",
  "celonis",
  "centrify",
  "centro",
  "cerebras",
  "cerner",
  "chainalysis",
  "charles schwab",
  "chase pay",
  "checkout.com",
  "checkr",
  "chewy",
  "chief",
  "chime",
  "circle",
  "circle internet financial",
  "cisco",
  "citadel",
  "citrix",
  "cityblock health",
  "civitas learning",
  "clari",
  "classpass",
  "clearcover",
  "clickup",
  "close",
  "close.io",
  "cloudbeds",
  "cloudera",
  "cloudflare",
  "cloudinary",
  "cloudstrike",
  "clubhouse",
  "coalition",
  "cockroach labs",
  "cocoon",
  "cohesity",
  "coinbase",
  "collage.com",
  "collective health",
  "collibra",
  "color",
  "commonbond",
  "commvault",
  "compass",
  "concur",
  "concur technologies",
  "confluent",
  "conga",
  "constellation software",
  "convene",
  "convergys",
  "convoy",
  "cornerstone",
  "coupa",
  "coupa software",
  "course hero",
  "coursera",
  "creatio",
  "credit karma",
  "crouchbase",
  "crowdcube",
  "crowdfunder",
  "culture amp",
  "curative",
  "curriculum asssociates",
  "cuvva",
  "cvent",
  "cybereason",
  "cybergrx",
  "cylance",
  "cylynt",
  "darktrace",
  "dassault",
  "databricks",
  "datadog",
  "dataiku",
  "dataminr",
  "datarobot",
  "datastax",
  "datev",
  "datorama",
  "datto",
  "dave",
  "deem",
  "deliverr",
  "dell",
  "dell technologies",
  "devoted health",
  "dfin",
  "dialogtech",
  "digital asset",
  "digital ocean",
  "digitalglobe",
  "digitalocean",
  "digitate",
  "disco",
  "discord",
  "discoverorg",
  "discovery digital media",
  "dispatchhealth",
  "divvy",
  "docker",
  "docusign",
  "domo",
  "doordash",
  "draftkings",
  "dremio",
  "drift",
  "dropbox",
  "druva",
  "duck creek",
  "duck creek technologies",
  "duolingo",
  "dutchie",
  "dwolla",
  "dynatrace",
  "e*trade",
  "e-trade",
  "ebay",
  "edx",
  "egnyte",
  "eightfold",
  "eightfold.ai",
  "elastic",
  "elastic.co",
  "emc",
  "enfusion",
  "enova",
  "epic",
  "epic games",
  "epicor",
  "epicor software",
  "eset",
  "esri",
  "ethereum",
  "etrade",
  "etsy",
  "eventbrite",
  "everbridge",
  "everlywell",
  "evernote",
  "ezcater",
  "facebook",
  "fair",
  "fair dialpad",
  "faire",
  "fanatics",
  "fanduel",
  "farmers business network",
  "fast enterprises",
  "fastly",
  "fico",
  "fig",
  "figma",
  "figure",
  "figure technologies",
  "fis",
  "fiserv",
  "fitsense",
  "five9",
  "fivetran",
  "flexport",
  "flipboard",
  "flockjay",
  "flywire",
  "formlabs",
  "forter",
  "fortinet",
  "forward financing",
  "freshworks",
  "friendsurance",
  "front",
  "fujitsu",
  "fullcontact",
  "fullstory",
  "fulutterwave",
  "funding circle",
  "fundrise",
  "fuse",
  "fuze",
  "gainsight",
  "ge healthcare",
  "genesys",
  "genesys telecommunications laboratories",
  "gfi software",
  "ginkgo bioworks",
  "github",
  "gitlab",
  "globality",
  "glossier",
  "goat",
  "gong",
  "gong.io",
  "good technology",
  "google",
  "gopro",
  "gopuff",
  "gospotcheck",
  "grammarly",
  "gravity payments",
  "greenlight",
  "greensky",
  "grove collaborative",
  "guaranteed rate",
  "guild education",
  "gusto",
  "gympass",
  "habito",
  "harness",
  "harry's",
  "harry's razor company",
  "hashicorp",
  "hawke media",
  "heartflow",
  "hellofresh",
  "hewlett packard",
  "hewlett-packard",
  "hexagon",
  "highradius",
  "highspot",
  "hinge health",
  "hitachi",
  "homeadvisor",
  "homeaway",
  "honey",
  "hotjar",
  "houzz",
  "hp",
  "hubspot",
  "hydrogen",
  "ibm",
  "ibotta",
  "icertis",
  "icims",
  "ihs markit",
  "ike",
  "illumio",
  "imedx",
  "impossible foods",
  "incertis",
  "indigo ag",
  "infinidat",
  "infor",
  "informatica",
  "inmobi",
  "innovaccer",
  "innovium",
  "insidesales",
  "instabase",
  "instacart",
  "intarcia therapeutics",
  "intel",
  "intel corporation",
  "intercom",
  "intersystems",
  "intralinks",
  "intuit",
  "invalua",
  "invision",
  "isn",
  "izettle",
  "jasper technologies",
  "jawbone",
  "jda software",
  "jet",
  "jfrog",
  "jobot",
  "jpmorgan chase",
  "just",
  "justfab",
  "justworks",
  "juul labs",
  "k health",
  "kabam",
  "kabbage",
  "kareo",
  "kaseya",
  "kasko",
  "kaspersky lab",
  "katerra",
  "keep truckin",
  "keeptruckin",
  "kendra scott",
  "kenna security",
  "kkw beauty",
  "klarna",
  "klaviyo",
  "knip",
  "knowbe4",
  "kong",
  "kraken",
  "kronos",
  "kronos incorporated",
  "kyriba",
  "lacework",
  "lattice",
  "launchdarkly",
  "legalzoom",
  "legendary entertainment",
  "lemonade",
  "lending club",
  "lendingclub",
  "lendinvest",
  "lendio",
  "lendup",
  "limeade",
  "linkedin",
  "liquid web",
  "liveperson",
  "lob",
  "locus robotics",
  "looker",
  "lookout",
  "loom",
  "lord abbett",
  "lower",
  "lu.com",
  "lucid",
  "lyell immunopharma",
  "lyft",
  "lynda",
  "lyra health",
  "machine zone",
  "magic leap",
  "magic software",
  "magic software enterprises",
  "magicleap",
  "mailchimp",
  "market finance",
  "marklogic",
  "marqueta",
  "masterclass",
  "mathworks",
  "mckesson",
  "medallia",
  "mediamath",
  "medidata",
  "meditech",
  "medtouch",
  "mendix",
  "mentor graphics",
  "meundies",
  "micro focus",
  "micros",
  "microsoft",
  "microstrategy",
  "mindstrong",
  "mint",
  "miro",
  "misys",
  "modern health",
  "modern tribe",
  "moderna therapeutics",
  "modernizing medicine",
  "monday.com",
  "moneyfarm",
  "mongodb",
  "monzo",
  "morningstar",
  "motorola",
  "moveon",
  "mozido",
  "mu sigma",
  "mulesoft",
  "mx",
  "mx technologies",
  "n26",
  "namely",
  "nanthealth",
  "navex global",
  "ncr",
  "nec",
  "nerdwallet",
  "netapp",
  "netdoor",
  "netflix",
  "netskope",
  "netspend",
  "netsuite",
  "neusoft",
  "new engen",
  "new relic",
  "newsela",
  "next insurance",
  "nextdoor",
  "nextiva",
  "niantic",
  "nice",
  "nielseniq",
  "nintex",
  "njoy",
  "noom",
  "notion",
  "notion labs",
  "ntwrk",
  "nuance communications",
  "nuro",
  "nutanix",
  "nutmeg",
  "nuvia",
  "nvidia",
  "o9 solutions",
  "ochard",
  "odoo",
  "okta",
  "olive",
  "on24",
  "ondeck",
  "onetrust",
  "openai",
  "openmarket",
  "opentext",
  "oportun",
  "opploans",
  "optiver",
  "optum",
  "oracle",
  "orca bio",
  "orchard",
  "oscar",
  "oscar health insurance",
  "outreach",
  "outsystems",
  "ownbackup",
  "p.volve",
  "pagerduty",
  "palantir",
  "papaya global",
  "partnercentric",
  "pat mcgrath labs",
  "patientpop",
  "patreon",
  "pax",
  "paycom",
  "paydiant",
  "payformance solutions",
  "paylocity",
  "paypal",
  "payscale",
  "pegasystems",
  "peloton",
  "pendo",
  "peopledoc",
  "personal capital",
  "pharmapacks",
  "pindrop security",
  "pinterest",
  "pipedrive",
  "pitchbook",
  "pitney bowes",
  "pivotal software",
  "planet labs",
  "playstation",
  "plume",
  "pluralsight",
  "podium",
  "pony ai",
  "pony.ai",
  "postman",
  "postmates",
  "powertofly",
  "pro.com",
  "procore",
  "procore technologies",
  "prodege",
  "proofpoint",
  "prosper marketplace",
  "proteus digital health",
  "ptc",
  "public",
  "pure storage",
  "pvolve",
  "qad",
  "qlik",
  "qualia",
  "qualtrics",
  "qualys",
  "quanergy",
  "quantcast",
  "quantum metric",
  "quibi",
  "quizlet",
  "qumulo",
  "quora",
  "radiology partners",
  "rani therapeutics",
  "rapid7",
  "ratesetter",
  "razer",
  "red hat",
  "red ventures",
  "reddit",
  "redfin",
  "redis labs",
  "reef",
  "reef technology",
  "relativity",
  "relativity space",
  "remitly",
  "rent the runway",
  "retailmenot",
  "return path",
  "ridgeline",
  "ringcentral",
  "ripple",
  "rippling",
  "riskified",
  "rivian",
  "ro",
  "robinhood",
  "roblox",
  "roivant sciences",
  "roku",
  "roost",
  "rubicon global",
  "rubrik",
  "sage",
  "sailpoint",
  "salesforce",
  "salesforce.com",
  "salesloft",
  "samsara",
  "samsara networks",
  "samumed",
  "sana benefits",
  "sap",
  "sap america",
  "sas",
  "sas institute",
  "savage x fenty",
  "scalable capital",
  "scale ai",
  "schneider electric",
  "schoology",
  "sciencelogic",
  "scopely",
  "seamless.ai",
  "securelink",
  "seedrs",
  "segment",
  "seismic",
  "sendoso",
  "sentinelone",
  "sentry",
  "servicenow",
  "servicetitan",
  "shazam",
  "shift technology",
  "shopkeep",
  "shyft analytics",
  "sidecar health",
  "siements",
  "sigfig",
  "sila nanotechnologies",
  "similarweb",
  "simplivity",
  "simplrflex",
  "sisense",
  "siteimprove",
  "skydance media",
  "skydio",
  "slack",
  "slice labs",
  "smartbear",
  "smartsheet",
  "sms assist",
  "snap",
  "snapchat",
  "snaplogic",
  "snowflake",
  "snyk",
  "social finance",
  "social solutions",
  "socialbakers",
  "socure",
  "sofi",
  "software ag",
  "solarwinds",
  "sonder",
  "soundhound",
  "spacex",
  "splashtop",
  "splunk",
  "spotify",
  "sprinklr",
  "square",
  "squarespace",
  "standard cognition",
  "starburst",
  "starling bank",
  "starry",
  "steelhouse",
  "stemcentrx",
  "steppie",
  "stockx",
  "strava",
  "stripe",
  "stryker",
  "sumo logic",
  "sumologic",
  "sungard",
  "sunrun",
  "suplari",
  "surveymonkey",
  "sweetgreen",
  "swift",
  "symantec",
  "symphony",
  "symphony communication services",
  "synopsys",
  "tableau",
  "tableau software",
  "tala",
  "talentica",
  "talentica software",
  "talkdesk",
  "tandem",
  "tango",
  "tangome",
  "tanium",
  "tealium",
  "teambrella",
  "techstyle fashion group",
  "tekion",
  "tempus",
  "teradata",
  "tesla",
  "the attachmate group",
  "the honest co.",
  "the honest company",
  "theranos",
  "thoughtspot",
  "thoughtworks",
  "thrasio",
  "thumbtack",
  "tibco",
  "tide",
  "tiktok",
  "tinder",
  "tipalti",
  "toast",
  "totvs",
  "trade desk",
  "tradeshift",
  "transferwise",
  "transparent",
  "transunion",
  "trella health",
  "trend micro",
  "tresata",
  "tripactions",
  "trueaccord",
  "trumid",
  "trustwave",
  "tula skincare",
  "tusimple",
  "twilio",
  "twitch",
  "twitter",
  "uber",
  "udacity",
  "udemy",
  "uipath",
  "ukg",
  "ultimate kronos group",
  "ultimate software",
  "unacast",
  "unit4",
  "unite us",
  "unity",
  "unity software",
  "unity technologies",
  "unqork",
  "upgrade",
  "upkey",
  "uplight",
  "uptake",
  "upwork",
  "uship",
  "ust global",
  "vacasa",
  "vanguard",
  "varo money",
  "vast data",
  "veeam",
  "veeva",
  "venafi",
  "venmo",
  "verifi",
  "verint",
  "verkada",
  "vertafore",
  "via transportation",
  "vice media",
  "villagemd",
  "virta health",
  "visa",
  "visma",
  "vmware",
  "vox media",
  "vrbo",
  "vts",
  "walkme",
  "warby parker",
  "warnermedia",
  "washington post",
  "wayfair",
  "wealthfront",
  "wealthsimple",
  "weave",
  "webflow",
  "webroot",
  "weee!",
  "wework",
  "whoop",
  "wincor nixdorf",
  "wish",
  "wolters kluwer",
  "wonolo",
  "workato",
  "workday",
  "workfront",
  "workiva",
  "workrise",
  "world wide technology",
  "worldremit",
  "wp engine",
  "ww",
  "wwt",
  "xactly",
  "xant",
  "xoom",
  "yapstone",
  "yardi",
  "yext",
  "yotpo",
  "you & mr jones",
  "younited credit",
  "zaloni",
  "zapier",
  "zayo",
  "zebra",
  "zebra technologies",
  "zendesk",
  "zenefits",
  "zenoti",
  "zestfinace",
  "zeta global",
  "zeta interactive",
  "zillow",
  "zipline",
  "ziprecruiter",
  "zocdoc",
  "zoho",
  "zoom",
  "zoominfo",
  "zscaler",
  "zulily",
  "zume",
  "zuora",
  "zwift",
  "zymergen",
  "zynga",
];

/*
Python script to convert new string to arr: 
=> arr = newString.split(", ")
Python script to log updated list: 
=> print(sorted(list(set(companies + arr))))

Note: 
=> companies array includes software companies, tech companies, fintech companies, startups, and unicorns
To optimize the array:
=> verify all .name companies (.com, .ai, .co, .io, inc.)
=> trim names of companies whose names are longer than 3 words, if applicable
=> technology/technologies/company/corporation/incorporated
*/

exports.companies = companies;
