const companies = [
  "10up",
  "23andme",
  "78 capital",
  "a cloud guru",
  "a10 networks",
  "abbvie",
  "abnormal security",
  "accenture",
  "accolade",
  "acerta pharma",
  "aci worldwide",
  "acorns",
  "actifio",
  "activecampaign",
  "activision",
  "acv auctions",
  "adaptive biotechnologies",
  "adepar",
  "adobe",
  "adp",
  "advanced micro devices, inc.",
  "advizr",
  "adyen",
  "affirm",
  "age of learning",
  "agero",
  "aha",
  "aha!",
  "airbnb",
  "airtable",
  "airwallex",
  "akamai",
  "akuna capital",
  "alarm.com",
  "aledade",
  "alibaba",
  "alkami",
  "allbirds",
  "allen institute",
  "allscripts",
  "allstate",
  "ally",
  "alphabet",
  "altair",
  "alteryx",
  "alto pharmacy",
  "alyce",
  "alzheon",
  "amazon",
  "amazon web services",
  "amazon.com",
  "amd",
  "american airlines",
  "american express",
  "american family insurance",
  "amex",
  "amgen",
  "amplitude",
  "analog devices",
  "anaplan",
  "ancestry",
  "anduril",
  "ansys",
  "apeel sciences",
  "apollo graphql",
  "appdirect",
  "appdynamics",
  "appen",
  "appfolio",
  "appian",
  "applause",
  "apple",
  "applied intuition",
  "applovin",
  "appnexus",
  "appsflyer",
  "apptio",
  "apsilon",
  "apttus",
  "argo ai",
  "arista",
  "arity",
  "armis",
  "artic wolf networks",
  "aruba",
  "asana",
  "asml",
  "assetz capital",
  "asurion",
  "at&t",
  "athenahealth",
  "atlassian",
  "atom",
  "attachmate group",
  "attentive",
  "auction.com",
  "audible",
  "aurora",
  "auth0",
  "autodesk",
  "automation anywhere",
  "automattic",
  "autonomic",
  "auxmoney",
  "avant",
  "avantcredit",
  "avature",
  "avaya",
  "avidxchange",
  "avigilon",
  "away",
  "aws",
  "axiom space",
  "axonius",
  "aza group",
  "azimo",
  "balyasny",
  "bamboohr",
  "bank of america",
  "barclays",
  "bcg digital ventures",
  "beeswax",
  "belvedere trading",
  "benchling",
  "benchlings",
  "bentley",
  "bento for business",
  "better",
  "better.com",
  "betterment",
  "betterup",
  "bigcommerce",
  "bigid",
  "bill",
  "bill.com",
  "billtrust",
  "bird rides",
  "bitpesa",
  "bitsight",
  "bitstamp",
  "blackbaud",
  "blackboard",
  "blackline",
  "blackrock",
  "blackstone",
  "blend",
  "blizzard",
  "blockfi",
  "bloom energy",
  "bloomberg",
  "blue apron",
  "blue yonder",
  "bluevine",
  "bmc",
  "bnp paribas",
  "bny mellon",
  "board",
  "bond street",
  "bondora",
  "boom supersonic",
  "bosch",
  "bought by many",
  "box",
  "box.com",
  "braintree",
  "branch",
  "braviant holdings",
  "braze",
  "brex",
  "bright healthcare",
  "brightinsight",
  "brooklinen",
  "bruva",
  "btc media",
  "buffer",
  "bungalow",
  "buzzfeed",
  "bytedance",
  "c2fo",
  "c3 ai",
  "c3.ai",
  "ca",
  "cadance",
  "calendly",
  "calm",
  "cambridge mobile telematics",
  "cameo",
  "candence design",
  "canoo",
  "canva",
  "capital group",
  "capital one",
  "capsule",
  "carbon",
  "carbon black",
  "carbon health",
  "carbon3d",
  "care.com",
  "cargurus",
  "carmax",
  "carta",
  "castlight",
  "cb insights",
  "cbre",
  "ccc",
  "ccc information",
  "cdw",
  "cedar",
  "celonis",
  "census",
  "centrify",
  "centro",
  "cerebras",
  "cerner",
  "certain lending",
  "chainalysis",
  "charles river",
  "charles schwab",
  "charthop",
  "chase pay",
  "checkout.com",
  "checkr",
  "chewy",
  "chicago trading",
  "chief",
  "chime",
  "circle",
  "circle internet",
  "cisco",
  "citadel",
  "citi",
  "citrix",
  "cityblock health",
  "civitas learning",
  "clari",
  "classpass",
  "clearbit",
  "clearcover",
  "clever",
  "clickup",
  "climate corporation",
  "close",
  "close.io",
  "cloudbeds",
  "cloudera",
  "cloudflare",
  "cloudinary",
  "cloudstrike",
  "clubhouse",
  "coalition",
  "cockroach labs",
  "cocoon",
  "coda",
  "codesandbox",
  "cohesity",
  "coinbase",
  "collage.com",
  "collective health",
  "collibra",
  "color",
  "comcast",
  "commonbond",
  "commvault",
  "compass",
  "concur",
  "confluent",
  "conga",
  "constellation",
  "convene",
  "convergys",
  "convoy",
  "cornerstone",
  "coupa",
  "coupang",
  "course hero",
  "coursera",
  "creatio",
  "credit karma",
  "credit suisse",
  "crouchbase",
  "crowdcube",
  "crowdfunder",
  "crowdstrike",
  "cruise",
  "culture amp",
  "curative",
  "curriculum associates",
  "curriculum asssociates",
  "cuvva",
  "cvent",
  "cybereason",
  "cybergrx",
  "cylance",
  "cylynt",
  "d.e. shaw",
  "darktrace",
  "dassault",
  "databricks",
  "datadog",
  "dataiku",
  "dataminr",
  "datarobot",
  "datastax",
  "datev",
  "datorama",
  "datto",
  "dave",
  "deem",
  "deliverr",
  "dell",
  "deutsche",
  "devoted health",
  "dfin",
  "dialogtech",
  "digital asset",
  "digital ocean",
  "digitalglobe",
  "digitalocean",
  "digitate",
  "disco",
  "discord",
  "discoverorg",
  "discovery digital",
  "disney",
  "dispatchhealth",
  "divvy",
  "docker",
  "docusign",
  "dolby",
  "doloitte",
  "domino data",
  "domo",
  "doordash",
  "draftkings",
  "dremio",
  "drift",
  "dropbox",
  "druva",
  "drw",
  "dtcc",
  "duck creek",
  "duolingo",
  "dutchie",
  "dwolla",
  "dynatrace",
  "e*trade",
  "e-trade",
  "ebay",
  "edx",
  "egnyte",
  "eightfold",
  "eightfold.ai",
  "elastic",
  "elastic.co",
  "electronic arts",
  "embark trucks",
  "emc",
  "enfusion",
  "enlitic",
  "enova",
  "eog",
  "epic",
  "epic games",
  "epic systems",
  "epicor",
  "eset",
  "esri",
  "ethereum",
  "etrade",
  "etsy",
  "eventbrite",
  "everbridge",
  "everlywell",
  "evernote",
  "expedia",
  "ezcater",
  "f5 networks",
  "facebook",
  "factset",
  "factual",
  "fair",
  "fair dialpad",
  "faire",
  "fanatics",
  "fanduel",
  "fannie mae",
  "farmers business network",
  "fast enterprises",
  "fastly",
  "fico",
  "fig",
  "figma",
  "figure",
  "finix",
  "fis",
  "fiserv",
  "fishtown analytics",
  "fitsense",
  "five rings",
  "five9",
  "fivetran",
  "flatiron",
  "flexport",
  "flipboard",
  "flockjay",
  "flywire",
  "formlabs",
  "forter",
  "fortinet",
  "fortressiq",
  "forward financing",
  "freshworks",
  "friendsurance",
  "front",
  "fujitsu",
  "fullcontact",
  "fullstory",
  "fulutterwave",
  "funding circle",
  "fundrise",
  "fuse",
  "fuze",
  "gainsight",
  "gap",
  "gatsby",
  "ge healthcare",
  "genentech",
  "general eletric",
  "genesys",
  "genesys telecommunications",
  "gfi",
  "ginkgo bioworks",
  "github",
  "gitlab",
  "globality",
  "glossier",
  "goat",
  "godaddy",
  "goldman sachs",
  "gong",
  "gong.io",
  "good technology",
  "google",
  "gopro",
  "gopuff",
  "gospotcheck",
  "grafana",
  "grammarly",
  "gravity payments",
  "greenlight",
  "greensky",
  "groupon",
  "grove collaborative",
  "grubhub",
  "guaranteed rate",
  "guidewire",
  "guild education",
  "gusto",
  "gympass",
  "habito",
  "harness",
  "harry's razor",
  "hashicorp",
  "hawke media",
  "hbo",
  "heartflow",
  "hellofresh",
  "hewlett packard",
  "hewlett-packard",
  "hexagon",
  "highradius",
  "highspot",
  "hinge health",
  "hitachi",
  "homeadvisor",
  "homeaway",
  "honest",
  "honest co.",
  "honey",
  "hotjar",
  "houzz",
  "hp",
  "hubspot",
  "hudson river",
  "hulu",
  "hydrogen",
  "ibm",
  "ibotta",
  "icertis",
  "icims",
  "ihs markit",
  "ike",
  "illumio",
  "imc",
  "imedx",
  "impossible foods",
  "incertis",
  "indeed",
  "indigo ag",
  "infinidat",
  "infor",
  "informatica",
  "inmobi",
  "innovaccer",
  "innovium",
  "insidesales",
  "instabase",
  "instacart",
  "intarcia therapeutics",
  "intel",
  "interactive brokers",
  "intercom",
  "intersystems",
  "intralinks",
  "intuit",
  "intuitive surgical",
  "invalua",
  "invision",
  "ironclad",
  "isn",
  "iterable",
  "izettle",
  "jane street",
  "jasper",
  "jawbone",
  "jda",
  "jefferies",
  "jet",
  "jfrog",
  "jobot",
  "jpmorgan",
  "jpmorgan chase",
  "jump trading",
  "just",
  "justfab",
  "justworks",
  "juul",
  "k health",
  "kabam",
  "kabbage",
  "kareo",
  "kaseya",
  "kasko",
  "kaspersky",
  "katerra",
  "keep truckin",
  "keeptruckin",
  "kendra scott",
  "kenna security",
  "khan academy",
  "kkw beauty",
  "kla",
  "klarna",
  "klaviyo",
  "knip",
  "knowbe4",
  "kong",
  "kraken",
  "kronos",
  "kyriba",
  "lacework",
  "lam research",
  "lattice",
  "launchdarkly",
  "legalzoom",
  "legendary entertainment",
  "leidos",
  "lemonade",
  "lending club",
  "lendingclub",
  "lendinvest",
  "lendio",
  "lendup",
  "leo",
  "lifion",
  "lime",
  "limeade",
  "linear",
  "linkedin",
  "liquid web",
  "liveperson",
  "lob",
  "locus robotics",
  "logdna",
  "looker",
  "lookout",
  "loom",
  "lord abbett",
  "lower",
  "lu.com",
  "lucid",
  "lumentum",
  "lyell immunopharma",
  "lyft",
  "lynda",
  "lyra",
  "lytx",
  "machine zone",
  "magic leap",
  "magic software",
  "magicleap",
  "mailchimp",
  "market axess",
  "market finance",
  "marklogic",
  "marqeta",
  "marqueta",
  "mastercard",
  "masterclass",
  "match",
  "mathworks",
  "mckesson",
  "medallia",
  "mediamath",
  "medidata",
  "meditech",
  "medtouch",
  "mendix",
  "mentor graphics",
  "meundies",
  "micro focus",
  "micros",
  "microsoft",
  "microstrategy",
  "millennium management",
  "mindstrong",
  "mint",
  "miro",
  "misys",
  "mitchell international",
  "mitek",
  "modern health",
  "modern treasury",
  "modern tribe",
  "moderna therapeutics",
  "modernizing medicine",
  "monday.com",
  "moneyfarm",
  "mongodb",
  "monte carlo",
  "monzo",
  "moogsoft",
  "moonshot factory",
  "morgan stanley",
  "morningstar",
  "motorola",
  "moveon",
  "mozido",
  "mu sigma",
  "mufg",
  "mulesoft",
  "mx",
  "n26",
  "namely",
  "nanthealth",
  "navex global",
  "ncr",
  "nec",
  "neo4j",
  "nerdwallet",
  "netapp",
  "netdoor",
  "netflix",
  "netlify",
  "netskope",
  "netspend",
  "netsuite",
  "neusoft",
  "new engen",
  "new relic",
  "new york times",
  "newsela",
  "next insurance",
  "nextdoor",
  "nextiva",
  "niantic",
  "nice",
  "nielseniq",
  "nintex",
  "njoy",
  "nokia",
  "nomura",
  "noom",
  "nordstrom",
  "nortonlifelock",
  "notion",
  "notion labs",
  "ntwrk",
  "nuance communications",
  "nuro",
  "nutanix",
  "nutmeg",
  "nuvia",
  "nvidia",
  "o9 solutions",
  "ochard",
  "odoo",
  "okta",
  "olive",
  "on24",
  "ondeck",
  "one medical",
  "onetrust",
  "open networking foundation",
  "openai",
  "opendoor",
  "opengov",
  "openmarket",
  "opentable",
  "opentext",
  "openx",
  "oportun",
  "opploans",
  "optimizely",
  "optiver",
  "optum",
  "oracle",
  "orca bio",
  "orchard",
  "oscar",
  "oscar health",
  "oscar health insurance",
  "osisoft",
  "outreach",
  "outsystems",
  "ownbackup",
  "p.volve",
  "pagerduty",
  "palantir",
  "palo alto networks",
  "pandora",
  "panther labs",
  "papaya global",
  "partnercentric",
  "pat mcgrath",
  "patientpop",
  "patreon",
  "pax",
  "paycom",
  "paydiant",
  "payformance solutions",
  "paylocity",
  "paypal",
  "payscale",
  "pegasystems",
  "peloton",
  "pendo",
  "peopledoc",
  "personal capital",
  "pharmapacks",
  "pindrop security",
  "pinterest",
  "pipedrive",
  "pitchbook",
  "pitney bowes",
  "pivotal software",
  "plaid",
  "planet labs",
  "plangrid",
  "playstation",
  "plume",
  "pluralsight",
  "pocket gems",
  "podium",
  "pony ai",
  "pony.ai",
  "postman",
  "postmates",
  "powertofly",
  "priceline",
  "privacera",
  "pro.com",
  "procore",
  "prodege",
  "productboard",
  "proofpoint",
  "prosper marketplace",
  "proteus digital",
  "prudential",
  "ptc",
  "public.com",
  "pulse secure",
  "pure storage",
  "pvolve",
  "qad",
  "qlik",
  "qualcomm",
  "qualia",
  "qualtrics",
  "qualys",
  "quanergy",
  "quantcast",
  "quantum metric",
  "quibi",
  "quickbase",
  "quizlet",
  "qumulo",
  "quora",
  "radiology partners",
  "rally health",
  "rani therapeutics",
  "rapid7",
  "ratesetter",
  "raytheon",
  "razer",
  "red hat",
  "red ventures",
  "reddit",
  "redfin",
  "redis labs",
  "reef",
  "relativity",
  "relativity space",
  "remitly",
  "rent the runway",
  "repl.it",
  "retailmenot",
  "retool",
  "return path",
  "rex homes",
  "ridgeline",
  "ringcentral",
  "riot games",
  "ripple",
  "ripple xpring",
  "rippling",
  "riskified",
  "rivian",
  "ro",
  "roam research",
  "robinhood",
  "roblox",
  "roivant sciences",
  "roku",
  "roost",
  "rubicon global",
  "rubrik",
  "sage",
  "sage bionetworks",
  "sailpoint",
  "salesforce",
  "salesforce.com",
  "salesloft",
  "samsara",
  "samsara networks",
  "samsung",
  "samumed",
  "sana benefits",
  "sap",
  "sap america",
  "sas",
  "sas institute",
  "savage x fenty",
  "scalable capital",
  "scale ai",
  "schneider electric",
  "schonfeld",
  "schoology",
  "sciencelogic",
  "scopely",
  "scribd",
  "seamless.ai",
  "seatgeek",
  "securelink",
  "seedrs",
  "segment",
  "seismic",
  "sendoso",
  "sentinelone",
  "sentry",
  "servicenow",
  "servicetitan",
  "shazam",
  "shift",
  "shopify",
  "shopkeep",
  "shutterfly",
  "shyft analytics",
  "sidecar health",
  "siements",
  "sig",
  "sigfig",
  "sigma computing",
  "sila nanotechnologies",
  "similarweb",
  "simplivity",
  "simplrflex",
  "sisense",
  "siteimprove",
  "sketch",
  "skillz",
  "skydance",
  "skydio",
  "slack",
  "slice labs",
  "smartbear",
  "smartsheet",
  "sms assist",
  "snap",
  "snapchat",
  "snaplogic",
  "snorkel ai",
  "snowflake",
  "snyk",
  "social finance",
  "social solutions",
  "socialbakers",
  "socotra",
  "socure",
  "sofi",
  "software ag",
  "solarwinds",
  "sonder",
  "sony",
  "soundhound",
  "spacex",
  "splashtop",
  "splunk",
  "spotify",
  "sprinklr",
  "square",
  "squarepoint",
  "squarespace",
  "standard cognition",
  "starburst",
  "starling bank",
  "starry",
  "steelhouse",
  "stemcentrx",
  "steppie",
  "stockx",
  "strava",
  "stripe",
  "stryker",
  "substack",
  "sumo logic",
  "sumologic",
  "sungard",
  "sunrun",
  "superhuman",
  "suplari",
  "surveymonkey",
  "sweetgreen",
  "swift",
  "symantec",
  "symphony",
  "symphony communication services",
  "synaptics",
  "synopsys",
  "tableau",
  "tala",
  "talentica",
  "talkdesk",
  "tandem",
  "tango",
  "tangome",
  "tanium",
  "tapad",
  "td securities",
  "tealium",
  "teambrella",
  "techstyle fashion group",
  "tekion",
  "tempus",
  "teradata",
  "tesla",
  "the hartford",
  "theranos",
  "thomson reuters",
  "thoughtspot",
  "thoughtworks",
  "thrasio",
  "thumbtack",
  "tibco",
  "tide",
  "tiktok",
  "tinder",
  "tipalti",
  "toast",
  "totvs",
  "trade desk",
  "tradeshift",
  "tradeweb",
  "transferwise",
  "transparent",
  "transunion",
  "trella",
  "trend micro",
  "tresata",
  "tripactions",
  "tripadvisor",
  "trueaccord",
  "trumid",
  "trustwave",
  "tsuru capital",
  "tula skincare",
  "tusimple",
  "twilio",
  "twitch",
  "twitter",
  "two sigma",
  "uber",
  "udacity",
  "udemy",
  "uipath",
  "ukg",
  "ultimate kronos group",
  "ultimate software",
  "unacast",
  "unit4",
  "unite us",
  "united airlines",
  "unitedhealth",
  "unity",
  "unqork",
  "upgrade",
  "upkey",
  "uplight",
  "uptake",
  "upwork",
  "uship",
  "ust global",
  "vacasa",
  "vanguard",
  "varo money",
  "vast data",
  "veeam",
  "veeva",
  "venafi",
  "venmo",
  "vercel",
  "verifi",
  "verily life sciences",
  "verint",
  "veritas",
  "verizon",
  "verkada",
  "vertafore",
  "via transportation",
  "viasat",
  "vice",
  "villagemd",
  "virta",
  "virtu financial",
  "visa",
  "visma",
  "vistaprint",
  "vmware",
  "volley",
  "voloen",
  "vox",
  "vrbo",
  "vts",
  "walkme",
  "walmart",
  "walmart labs",
  "walt disney",
  "warby parker",
  "warnermedia",
  "washington post",
  "wayfair",
  "waymo",
  "wealthfront",
  "wealthsimple",
  "weave",
  "webflow",
  "webroot",
  "weee!",
  "wells fargo",
  "wepay",
  "western asset",
  "wework",
  "whoop",
  "wincor nixdorf",
  "wish",
  "wolters kluwer",
  "wolverine trading",
  "wonolo",
  "workato",
  "workday",
  "workfront",
  "workiva",
  "workrise",
  "world wide",
  "worldpay",
  "worldremit",
  "wp engine",
  "ww",
  "wwt",
  "xactly",
  "xant",
  "xoom",
  "yahoo",
  "yapstone",
  "yardi",
  "yelp",
  "yext",
  "yotpo",
  "you & mr jones",
  "younited credit",
  "zaloni",
  "zapier",
  "zayo",
  "zebra",
  "zendesk",
  "zenefits",
  "zenoti",
  "zestfinace",
  "zeta global",
  "zeta interactive",
  "zillow",
  "zipline",
  "ziprecruiter",
  "zocdoc",
  "zoho",
  "zoom",
  "zoominfo",
  "zoox",
  "zscaler",
  "zulily",
  "zume",
  "zuora",
  "zwift",
  "zymergen",
  "zynga",
];

/*
Python script to add companies from newString: 
newString = ""
arr = newString.split(", ")
print(sorted(list(set(companies + arr))))

Note: 
=> companies array includes software companies, tech companies, fintech companies, startups, and unicorns
To optimize the array:
=> verify all .name companies (.com, .ai, .io, .co, inc., co.)
=> trim names of companies whose names are longer than 3 words, if applicable
=> remove the words technology/technologies/company/corporation/incorporated/systems/software/financial/media/services/labs/health
   from company names, if applicable
*/

exports.companies = companies;
